cardano_keri_metadata = {
  ? uint => auth_event
}

auth_event = 
  auth_begin /
  auth_end /
  attest /
  attest_tx /
  claim_tx

auth_begin = {
  t: "AUTH_BEGIN",
  s: text,          ; SAID of leaf credential schema
  i: text,          ; AID of signer
  c: bytes,         ; Byte stream payload
  ? m: metadata_map ; Optional metadata
}

attest = {
  t: "ATTEST",
  i: text,          ; AID of signer
  d: text,          ; Digest
  s: text           ; Hex-encoded sequence number
}

attest_tx = {
  t: "ATTEST_TX",
  i: text,          ; AID of signer
  ? s: text,        ; Hex-encoded sequence number hint
  v: cip_version
}

claim_tx = {
  t: "CLAIM_TX",
  i: text,          ; AID of signer
  r: [+ tx_id],     ; Claimed transactions
  ? s: text,        ; Hex-encoded sequence number hint
  v: cip_version
}

tx_id = text .regexp "[0-9a-f]{64}"  ; Lowercase hex transaction ID

cip_version = {
  v: text           ; CIP version, "1.1" or later
}

auth_end = {
  t: "AUTH_END",
  s: text,          ; SAID of leaf credential schema
  i: text,          ; AID of signer
  c: bytes,         ; Byte stream payload
  ? m: metadata_map ; Optional metadata
}

metadata_map = {
  * text => any
}
